# coding: utf-8
group = {
    'groupId':
    8271,
    'groupName':
    'Deadringer',
    'artist':
    'Rjd2',
    'cover':
    'https://ptpimg.me/6yf0gx.jpg',
    'tags':
    ['hip.hop', 'electronic', '2000s', 'instrumental', 'ohio', 'columbus', 'trip.hop'],
    'bookmarked':
    False,
    'vanityHouse':
    False,
    'groupYear':
    2002,
    'releaseType':
    'Album',
    'groupTime':
    '1489612139',
    'maxSize':
    1266323049,
    'totalSnatched':
    334,
    'totalSeeders':
    202,
    'totalLeechers':
    2,
    'torrents': [{
        'torrentId': 967477,
        'editionId': 1,
        'artists': [{
            'id': 8745,
            'name': 'Rjd2',
            'aliasid': 746053
        }],
        'remastered': True,
        'remasterYear': 2002,
        'remasterCatalogueNumber': 'DJX35',
        'remasterTitle': 'Reissue',
        'media': 'CD',
        'encoding': 'Lossless',
        'format': 'FLAC',
        'hasLog': True,
        'logScore': 100,
        'hasCue': True,
        'scene': False,
        'vanityHouse': False,
        'fileCount': 20,
        'time': '2017-03-15 21:08:59',
        'size': 387592617,
        'snatches': 175,
        'seeders': 106,
        'leechers': 1,
        'isFreeleech': False,
        'isNeutralLeech': False,
        'isPersonalFreeleech': False,
        'canUseToken': True,
        'hasSnatched': False
    }, {
        'torrentId': 94046,
        'editionId': 1,
        'artists': [{
            'id': 8745,
            'name': 'Rjd2',
            'aliasid': 746053
        }],
        'remastered': True,
        'remasterYear': 2002,
        'remasterCatalogueNumber': 'DJX35',
        'remasterTitle': 'Reissue',
        'media': 'CD',
        'encoding': '320',
        'format': 'MP3',
        'hasLog': False,
        'logScore': 0,
        'hasCue': False,
        'scene': False,
        'vanityHouse': False,
        'fileCount': 17,
        'time': '2016-11-28 13:00:05',
        'size': 161950294,
        'snatches': 8,
        'seeders': 6,
        'leechers': 0,
        'isFreeleech': False,
        'isNeutralLeech': False,
        'isPersonalFreeleech': False,
        'canUseToken': True,
        'hasSnatched': False
    }, {
        'torrentId': 28457,
        'editionId': 1,
        'artists': [{
            'id': 8745,
            'name': 'Rjd2',
            'aliasid': 746053
        }],
        'remastered': True,
        'remasterYear': 2002,
        'remasterCatalogueNumber': 'DJX35',
        'remasterTitle': 'Reissue',
        'media': 'CD',
        'encoding': 'V0 (VBR)',
        'format': 'MP3',
        'hasLog': False,
        'logScore': 0,
        'hasCue': False,
        'scene': False,
        'vanityHouse': False,
        'fileCount': 19,
        'time': '2016-11-26 23:44:29',
        'size': 106226753,
        'snatches': 68,
        'seeders': 26,
        'leechers': 0,
        'isFreeleech': False,
        'isNeutralLeech': False,
        'isPersonalFreeleech': False,
        'canUseToken': True,
        'hasSnatched': False
    }, {
        'torrentId': 805045,
        'editionId': 2,
        'artists': [{
            'id': 8745,
            'name': 'Rjd2',
            'aliasid': 746053
        }],
        'remastered': True,
        'remasterYear': 2002,
        'remasterCatalogueNumber': 'DJX35',
        'remasterTitle': 'Reissue',
        'media': 'Vinyl',
        'encoding': 'V0 (VBR)',
        'format': 'MP3',
        'hasLog': False,
        'logScore': 0,
        'hasCue': False,
        'scene': False,
        'vanityHouse': False,
        'fileCount': 23,
        'time': '2017-01-27 23:14:29',
        'size': 110123521,
        'snatches': 1,
        'seeders': 3,
        'leechers': 0,
        'isFreeleech': False,
        'isNeutralLeech': False,
        'isPersonalFreeleech': False,
        'canUseToken': True,
        'hasSnatched': False
    }, {
        'torrentId': 775269,
        'editionId': 3,
        'artists': [{
            'id': 8745,
            'name': 'Rjd2',
            'aliasid': 746053
        }],
        'remastered': True,
        'remasterYear': 2009,
        'remasterCatalogueNumber': 'RJEC004',
        'remasterTitle': '',
        'media': 'Vinyl',
        'encoding': '24bit Lossless',
        'format': 'FLAC',
        'hasLog': False,
        'logScore': 0,
        'hasCue': False,
        'scene': False,
        'vanityHouse': False,
        'fileCount': 26,
        'time': '2017-01-22 16:46:51',
        'size': 1266323049,
        'snatches': 22,
        'seeders': 9,
        'leechers': 0,
        'isFreeleech': False,
        'isNeutralLeech': False,
        'isPersonalFreeleech': False,
        'canUseToken': True,
        'hasSnatched': False
    }, {
        'torrentId': 783146,
        'editionId': 3,
        'artists': [{
            'id': 8745,
            'name': 'Rjd2',
            'aliasid': 746053
        }],
        'remastered': True,
        'remasterYear': 2009,
        'remasterCatalogueNumber': 'RJEC004',
        'remasterTitle': '',
        'media': 'Vinyl',
        'encoding': 'Lossless',
        'format': 'FLAC',
        'hasLog': False,
        'logScore': 0,
        'hasCue': False,
        'scene': False,
        'vanityHouse': False,
        'fileCount': 26,
        'time': '2017-01-23 23:01:05',
        'size': 344485492,
        'snatches': 1,
        'seeders': 4,
        'leechers': 0,
        'isFreeleech': False,
        'isNeutralLeech': False,
        'isPersonalFreeleech': False,
        'canUseToken': True,
        'hasSnatched': False
    }, {
        'torrentId': 828020,
        'editionId': 3,
        'artists': [{
            'id': 8745,
            'name': 'Rjd2',
            'aliasid': 746053
        }],
        'remastered': True,
        'remasterYear': 2009,
        'remasterCatalogueNumber': 'RJEC004',
        'remasterTitle': '',
        'media': 'Vinyl',
        'encoding': '320',
        'format': 'MP3',
        'hasLog': False,
        'logScore': 0,
        'hasCue': False,
        'scene': False,
        'vanityHouse': False,
        'fileCount': 26,
        'time': '2017-02-01 20:59:09',
        'size': 145220442,
        'snatches': 0,
        'seeders': 3,
        'leechers': 0,
        'isFreeleech': False,
        'isNeutralLeech': False,
        'isPersonalFreeleech': False,
        'canUseToken': True,
        'hasSnatched': False
    }, {
        'torrentId': 784643,
        'editionId': 3,
        'artists': [{
            'id': 8745,
            'name': 'Rjd2',
            'aliasid': 746053
        }],
        'remastered': True,
        'remasterYear': 2009,
        'remasterCatalogueNumber': 'RJEC004',
        'remasterTitle': '',
        'media': 'Vinyl',
        'encoding': 'V0 (VBR)',
        'format': 'MP3',
        'hasLog': False,
        'logScore': 0,
        'hasCue': False,
        'scene': False,
        'vanityHouse': False,
        'fileCount': 26,
        'time': '2017-01-24 06:18:38',
        'size': 118515017,
        'snatches': 1,
        'seeders': 3,
        'leechers': 0,
        'isFreeleech': False,
        'isNeutralLeech': False,
        'isPersonalFreeleech': False,
        'canUseToken': True,
        'hasSnatched': False
    }, {
        'torrentId': 114995,
        'editionId': 4,
        'artists': [{
            'id': 8745,
            'name': 'Rjd2',
            'aliasid': 746053
        }],
        'remastered': True,
        'remasterYear': 2009,
        'remasterCatalogueNumber': 'RJEC004',
        'remasterTitle': '',
        'media': 'CD',
        'encoding': 'Lossless',
        'format': 'FLAC',
        'hasLog': True,
        'logScore': 100,
        'hasCue': True,
        'scene': False,
        'vanityHouse': False,
        'fileCount': 20,
        'time': '2016-11-29 01:02:41',
        'size': 457896681,
        'snatches': 40,
        'seeders': 32,
        'leechers': 1,
        'isFreeleech': False,
        'isNeutralLeech': False,
        'isPersonalFreeleech': False,
        'canUseToken': True,
        'hasSnatched': False
    }, {
        'torrentId': 199611,
        'editionId': 4,
        'artists': [{
            'id': 8745,
            'name': 'Rjd2',
            'aliasid': 746053
        }],
        'remastered': True,
        'remasterYear': 2009,
        'remasterCatalogueNumber': 'RJEC004',
        'remasterTitle': '',
        'media': 'CD',
        'encoding': 'V0 (VBR)',
        'format': 'MP3',
        'hasLog': False,
        'logScore': 0,
        'hasCue': False,
        'scene': False,
        'vanityHouse': False,
        'fileCount': 20,
        'time': '2016-12-02 21:00:28',
        'size': 140306805,
        'snatches': 12,
        'seeders': 9,
        'leechers': 0,
        'isFreeleech': False,
        'isNeutralLeech': False,
        'isPersonalFreeleech': False,
        'canUseToken': True,
        'hasSnatched': False
    }, {
        'torrentId': 380821,
        'editionId': 5,
        'artists': [{
            'id': 8745,
            'name': 'Rjd2',
            'aliasid': 746053
        }],
        'remastered': True,
        'remasterYear': 2015,
        'remasterCatalogueNumber': 'RJEC004',
        'remasterTitle': '',
        'media': 'WEB',
        'encoding': '320',
        'format': 'MP3',
        'hasLog': False,
        'logScore': 0,
        'hasCue': False,
        'scene': False,
        'vanityHouse': False,
        'fileCount': 19,
        'time': '2016-12-10 17:03:38',
        'size': 172928479,
        'snatches': 6,
        'seeders': 1,
        'leechers': 0,
        'isFreeleech': False,
        'isNeutralLeech': False,
        'isPersonalFreeleech': False,
        'canUseToken': True,
        'hasSnatched': False
    }]
}
